GET http://localhost:8001/users?page=1&size=20
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZsYWRpbWlyIiwiaWF0IjoxNjQ0NTA3MjAxLCJleHAiOjMyODkzNzQ0MDIsImlzcyI6ImNvb2xJc3N1ZXIifQ.jiZXhUwujcFZR_kOyPjnRRQxq9IvEic7tLJ3Ue0wpuQ